id: P54B71994
initial_creation_type: ocr
source_metadata:
  volumes:
    010fae9baf1b46a0a9f0030191575211:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: རལ་གཅིག་མའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1648
      volume_number: 40
